### ISSUE TITLE
提供的代码缺少东西

### ISSUE THREAD

**Issue by yudawen** [XinnHe/ST-UNet#2]
同学，你提供的代码好像缺少东西，能不能整理一个只包括网络部分的文件，就网络结构部分就好，非常感谢。

**Comment by XinnHe** [comment]
有网络的文件啊在networks/里，我是在transUNet基础上改的，所以还用的TransUnet里的文件名，但是里面是我的结构





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XinnHe/ST-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午4:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[XinnHe/ST-UNet] 提供的代码缺少东西 (Issue #2)





 
大哥，你提供的代码缺少东西，能不能整理一个包括网络部分的文件，训练和测试的代码不需要，就网络结构部分就好，非常感谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XinnHe** [comment]
我是女生😅

**Comment by yudawen** [comment]
from functions.modulated_dcn_func import ModulatedDeformConvFunction
from functions.modulated_dcn_func import DeformRoIPoolingFunction
这2个函数在代码里面好像木有！

**Comment by XinnHe** [comment]
那个没关系，你可以把modulated_dcn.py这个文件删了，没用这个，我调用的deform_conv.py 完成可变形卷积。
![image](https://user-images.githubusercontent.com/40020691/156993806-9ccd2cba-6653-4496-9ed5-0b5af9d94e37.png)

**Comment by XinnHe** [comment]
这两个文件都能实现可变形卷积，我最后使用了deform_conv.

**Comment by yudawen** [comment]
![QQ图片20220309111557](https://user-images.githubusercontent.com/33175103/157365974-1341e06d-3a76-4538-9161-a9672e81d3b3.png)
文中这里少一个图片的id

**Comment by yudawen** [comment]
还有你的网络可以加预训练模型吗，我看在这个数据集上加不加ImageNet预训练模型差别很大的

**Comment by yudawen** [comment]
TransUNet我加预训练权重mIoU有76%多

**Comment by XinnHe** [comment]
可以加，我没加




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XinnHe/ST-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XinnHe/ST-UNet] 提供的代码缺少东西 (Issue #2)





 
小姐姐，还有你的网络可以加预训练模型吗，我看在这个数据集上加不加ImageNet预训练模型差别很大的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XinnHe** [comment]
这里写漏了一个6_13,我都没发现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XinnHe/ST-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XinnHe/ST-UNet] 提供的代码缺少东西 (Issue #2)





 

 这个少一个图片的id
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yudawen** [comment]
ResNetv2的权重吗 你能测试一下是否可以加吗
我感觉加预训练模型精度会提高很多，你论文中对比的方法是都没有使用预训练权重吗

**Comment by yudawen** [comment]
训练的时候出现nan你有遇到吗

**Comment by XinnHe** [comment]
我都没加预训练模型。没有出现nan，你查下是不是你的数据加载有问题

**Comment by Wangyz1021** [comment]
大哥，这个模块为什么pip不了？你怎么弄的
![image](https://user-images.githubusercontent.com/93376271/165082393-4eae7e76-9327-4e08-9d2a-05498ce25b9a.png)

**Comment by Wangyz1021** [comment]
请问一下数据集使用的请哪个
![image](https://user-images.githubusercontent.com/93376271/165440380-888603c9-1504-4805-bd51-1f5ed4354822.png)

**Comment by xinjiTian** [comment]
> 训练的时候出现nan你有遇到吗

同学 可以提供一下你的softpool部分的代码吗 感谢

**Comment by ZCX-11** [comment]
同学你好，请问你softpool部分是怎么安装的，具体步骤告诉一下，谢谢

**Comment by ZCX-11** [comment]
您好，请问那个softpool部分是怎么安装，具体步骤能说一下吗，我按照网上步骤，没能安装上，请您指点

**Comment by Wangyz1021** [comment]
去github下载了这个东西，然后在这个项目的conda环境里面pip安装












Wang
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XinnHe/ST-UNet] 提供的代码缺少东西 (Issue #2)

**Comment by ZCX-11** [comment]
您好，我对这方面刚接触不久，对一些操作还不是很熟悉，您能将安装SoftPool步骤说的详细一点，将一些命令行命令告诉一下，谢谢

**Comment by Wangyz1021** [comment]
我大概是四五月份吧，看了这个东西，就算是你安成功了也没有用，作者提供的东西就是个垃圾，根本不规范，问了人家也不回，不知道他们咋做出来的成功，你不要安这个东西你先看看人家代码，那是啥嘛，安了也没有用，后面后续还有很多问题，就这样。
随便看看参考一下吧。












Wang
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XinnHe/ST-UNet] 提供的代码缺少东西 (Issue #2)




 
您好，我对这方面刚接触不久，对一些操作还不是很熟悉，您能将安装SoftPool步骤说的详细一点，将一些命令行命令告诉一下，谢谢

**Comment by yudawen** [comment]
@ZCX-11 https://github.com/rentainhe/pytorch-pooling/blob/master/Pooling/pooling_method/softpool.py softpool我是直接用这个文件里面的代码，不需要编译安装。
@Wangyz1021 作者把代码公开，对遥感社区的发展是有贡献的，你这样讲真的不好

**Comment by ZCX-11** [comment]
> @ZCX-11 https://github.com/rentainhe/pytorch-pooling/blob/master/Pooling/pooling_method/softpool.py softpool我是直接用这个文件里面的代码，不需要编译安装。 @Wangyz1021 作者把代码公开，对遥感社区的发展是有贡献的，你这样讲真的不好

非常感谢

**Comment by yuanlu628-stack** [comment]
> 有网络的文件啊在networks/里，我是在transUNet基础上改的，所以还用的TransUnet里的文件名，但是里面是我的结构
> […](#)

您好，能提供一下您的切分的数据集的代码嘛或者是切好的数据，我在官网下载之后切分和您的对不齐，真的很需要，谢谢
